Vagrant.configure("2") do |config| 
  config.vm.box = "gyptazy/centos9-arm64" 
  config.vm.box_version = "1.0.0"
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.ssh_info_public = true
    vmware.gui = true
    vmware.allowlist_verified = true
    vmware.linked_clone = false
    vmware.vmx["ethernet0.virtualdev"] = "vmxnet3"
   end
 end
